# Generated by Django 4.2.15 on 2025-12-15 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content in soil (kg/ha)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content in soil (kg/ha)')),
                ('potassium', models.FloatField(help_text='Potassium content in soil (kg/ha)')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity in %')),
                ('ph', models.FloatField(help_text='pH value of the soil')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('recommended_crop', models.CharField(help_text='Recommended crop', max_length=100)),
                ('confidence', models.FloatField(blank=True, help_text='Prediction confidence', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Recommendation',
                'verbose_name_plural': 'Crop Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
